#pragma once
#include "dif.hpp"
#include "make_cos_table.hpp"
#include "qd_fft.hpp"
#include "sixstep.hpp"
#include "sixstep_omp.hpp"
#include "stockham.hpp"
#include "stockham_gpu.hpp"
#include "stockham_omp.hpp"